apiVersion: v1
kind: PersistentVolume
metadata:
  name: credentials-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/genius-project-AAAAAA/shared
    type: Directory
