apiVersion: v1
kind: Namespace
metadata:
  name: task-2-namespace

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: task-2-namespace
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress